export const HeadersRecord: Record<string, string> = {
  case_number: 'Broj predmeta',
  contract_number: 'Broj ugovora',
  name: 'Ime i prezime / Ime firme',
  is_legal: 'Pravno lice',
  package: 'Paket',
  principal: 'Osnovni dug',
  interest: 'Kamata',
  cession: 'Cesija',
  state: 'Aktivan',
  phone_number_1: 'Broj telefona 1',
  phone_number_2: 'Broj telefona 2',
  phone_number_3: 'Broj telefona 3',
  phone_number_4: 'Broj telefona 4',
  zip_code: 'Zip kod',
  city: 'Grad',
  address: 'Adresa',
  employed: 'Zaposlenje',
  employer: 'Poslodavac',
  jmbg_pib: 'JMBG / PIB',
  lawyer: 'Advokat',
  ssn: 'SSN',
  executor_1: 'Izvršitelj 1',
  executor_2: 'Izvršitelj 2',
  business_number_1: 'Poslovni broj (IVK) 1',
  business_number_2: 'Poslovni broj (IVK) 2',
};
